spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/babies
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  devtools:
    restart:
      enabled: false
    liveload:
      enabled: false
#  messages:
#    basename: i18n/deverrors
#    cache-duration: 3600
#    encoding: UTF-8
#    always-use-message-format: false
#    fallback-to-system-locale: true
#    use-code-as-default-message: false
  http:
    encoding:
      force: true
server:
  port: 8000

admin:
  name: vidor
  password: vidor
  content: ${admin.name} + ${admin.password}

user1: test
user2: test2