spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/babies
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  devtools:
    restart:
      enabled: false
    liveload:
      enabled: false

server:
  port: 8000

admin:
  name: vidor
  password: vidor
  content: ${admin.name} + ${admin.password}

user1: test
user2: test2